class AppStrings {
  static final Map<String, Map<String, String>> _localizedValues = {
    'ru': {
      'search': 'Поиск',
      'tasks': 'Задачи',
      'settings': 'Настройки',
      'create_folder': 'Создать папку',
      'create_task': 'Создать задачу',
      'new_task': 'новая задача...',
      'new_folder': 'новая папка...',
      'delete': 'Удалить',
      'edit': 'Редактировать',
      'edit_task': 'Редактировать задачу',
      'edit_folder': 'Редактировать папку',
      'delete_folder': 'Удалить папку',
      'cancel': 'Отмена',
      'save': 'Сохранить',
      'empty_list': 'Список пуст',
      'nothing_found': 'Ничего не найдено',
      'filters': 'Фильтры',
      'filter_all': 'Все',
      'filter_active': 'В процессе',
      'filter_completed': 'Завершенные',
      'filter_folders': 'Только папки',
      'change_avatar': 'Сменить аватар',
      'notifications': 'Уведомления',
      'theme': 'Тема приложения',
      'data_management': 'Управление данными',
      'language': 'Язык',
      'lang_name': 'русский',
      'animation_speed': 'Плавность анимации',
      'speed_fast': 'Быстро',
      'speed_normal': 'Обычно',
      'speed_slow': 'Медленно',
      'speed_custom': 'Своя',
      'about': 'О приложении',
      'about_title': 'О приложении ASA',
      'about_desc': 'ASA — современный менеджер задач с поддержкой папок и гибкой фильтрацией.',
      'version': 'Версия 1.0.0',
      'clear_tasks': 'Очистить все задачи',
      'clear_folders': 'Очистить все папки',
      'clear_all': 'Сбросить все данные',
      'confirm_clear': 'Вы уверены?',
      'folder_title': 'Папка: ',
      'no_tasks_in_folder': 'В этой папке пока нет задач',
      'add_task_to_folder': 'Добавить задачу в папку',
      'back': 'Назад',
      'confirm_delete_title': 'Удаление',
      'confirm_delete_content': 'Вы уверены, что хотите удалить это?',
      'speed_range': 'от 0.1 до 5.0',
      'speed_error': 'Значение должно быть от 0.1 до 5.0',
      'save_btn': 'Сохранить',
      'task_moved': 'Задача перенесена в',
      'folder_moved': 'Папка перенесена в',
      'widget': 'Виджет',
      'show_in_widget': 'Показывать задачи в виджете',
      'widget_mode': 'Что отображать',
      'widget_mode_streak': 'Стрик',
      'widget_mode_active_tasks': 'Активные задачи',
      'widget_mode_last_folder': 'Последняя папка',
      'widget_disabled': 'Виджет выключен',
      'widget_last_folder': 'Последняя папка',
    },
    'en': {
      'search': 'Search',
      'tasks': 'Tasks',
      'settings': 'Settings',
      'create_folder': 'Create folder',
      'create_task': 'Create task',
      'new_task': 'new task...',
      'new_folder': 'new folder...',
      'delete': 'Delete',
      'edit': 'Edit',
      'edit_task': 'Edit task',
      'edit_folder': 'Edit folder',
      'delete_folder': 'Delete folder',
      'cancel': 'Cancel',
      'save': 'Save',
      'empty_list': 'List is empty',
      'nothing_found': 'Nothing found',
      'filters': 'Filters',
      'filter_all': 'All',
      'filter_active': 'In progress',
      'filter_completed': 'Completed',
      'filter_folders': 'Folders only',
      'change_avatar': 'Change avatar',
      'notifications': 'Notifications',
      'theme': 'App theme',
      'data_management': 'Data management',
      'language': 'Language',
      'lang_name': 'English',
      'animation_speed': 'Animation speed',
      'speed_fast': 'Fast',
      'speed_normal': 'Normal',
      'speed_slow': 'Slow',
      'speed_custom': 'Custom',
      'about': 'About app',
      'about_title': 'About ASA App',
      'about_desc': 'ASA is a modern task manager supporting folders and flexible filtering.',
      'version': 'Version 1.0.0',
      'clear_tasks': 'Clear all tasks',
      'clear_folders': 'Clear all folders',
      'clear_all': 'Reset all data',
      'confirm_clear': 'Are you sure?',
      'folder_title': 'Folder: ',
      'no_tasks_in_folder': 'No tasks in this folder yet',
      'add_task_to_folder': 'Add task to folder',
      'back': 'Back',
      'confirm_delete_title': 'Delete',
      'confirm_delete_content': 'Are you sure you want to delete this?',
      'speed_range': 'from 0.1 to 5.0',
      'speed_error': 'Value must be between 0.1 and 5.0',
      'save_btn': 'Save',
      'task_moved': 'Task moved to',
      'folder_moved': 'Folder moved to',
      'widget': 'Widget',
      'show_in_widget': 'Show tasks in widget',
      'widget_mode': 'What to display',
      'widget_mode_streak': 'Streak',
      'widget_mode_active_tasks': 'Active tasks',
      'widget_mode_last_folder': 'Last folder',
      'widget_disabled': 'Widget disabled',
      'widget_last_folder': 'Last folder',
    },
  };

  static String get(String key, String lang) {
    return _localizedValues[lang]?[key] ?? _localizedValues['ru']?[key] ?? key;
  }
}
