class AppStrings {
  static final Map<String, Map<String, String>> _localizedValues = {
    'ru': {
      'search': 'Поиск',
      'tasks': 'Задачи',
      'settings': 'Настройки',
      'create_folder': 'Создать папку',
      'create_task': 'Создать задачу',
      'new_task': 'новая задача...',
      'new_folder': 'новая папка...',
      'delete': 'Удалить',
      'edit': 'Редактировать',
      'edit_task': 'Редактировать задачу',
      'edit_folder': 'Редактировать папку',
      'delete_folder': 'Удалить папку',
      'cancel': 'Отмена',
      'save': 'Сохранить',
      'empty_list': 'Список пуст',
      'nothing_found': 'Ничего не найдено',
      'filters': 'Фильтры',
      'filter_all': 'Все',
      'filter_active': 'В процессе',
      'filter_completed': 'Завершенные',
      'filter_folders': 'Только папки',
      'change_avatar': 'Сменить аватар',
      'notifications': 'Уведомления',
      'profile': 'Профиль',
      'appearance': 'Внешний вид',
      'widgets': 'Виджеты',
      'notifications_and_data': 'Уведомления и данные',
      'other': 'Другое',
      'theme': 'Тема приложения',
      'theme_light': 'Светлая',
      'theme_dark': 'Тёмная',
      'theme_system': 'Системная',
      'data_management': 'Управление данными',
      'language': 'Язык',
      'lang_name': 'русский',
      'animation_speed': 'Плавность анимации',
      'speed_fast': 'Быстро',
      'speed_normal': 'Обычно',
      'speed_slow': 'Медленно',
      'speed_custom': 'Своя',
      'app_scale': 'Масштаб интерфейса',
      'scale_small': 'Мелкий',
      'scale_default': 'Стандарт',
      'scale_large': 'Крупный',
      'scale_custom': 'Свой',
      'about': 'О приложении',
      'about_title': 'О приложении ASA',
      'about_desc': 'ASA — современный менеджер задач с поддержкой папок и гибкой фильтрацией.',
      'version': 'Версия 1.1.0',
      'clear_tasks': 'Очистить все задачи',
      'clear_folders': 'Очистить все папки',
      'clear_all': 'Сбросить все данные',
      'confirm_clear': 'Вы уверены?',
      'folder_title': 'Папка: ',
      'no_tasks_in_folder': 'В этой папке пока нет задач',
      'add_task_to_folder': 'Добавить задачу в папку',
      'back': 'Назад',
      'confirm_delete_title': 'Удаление',
      'confirm_delete_content': 'Вы уверены, что хотите удалить это?',
      'speed_range': 'от 0.1 до 5.0',
      'speed_error': 'Значение должно быть от 0.1 до 5.0',
      'scale_error': 'Значение должно быть в пределах допустимого диапазона',
      'save_btn': 'Сохранить',
      'streak_info': 'О стрике',
      'task_moved': 'Задача перенесена в',
      'folder_moved': 'Папка перенесена в',
      'widget': 'Виджет',
      'show_in_widget': 'Показывать задачи в виджете',
      'widget_mode': 'Что отображать',
      'widget_mode_streak': 'Стрик',
      'widget_mode_active_tasks': 'Активные задачи',
      'widget_mode_last_folder': 'Последняя папка',
      'widget_disabled': 'Виджет выключен',
      'widget_last_folder': 'Последняя папка',
      'update_available': 'Доступно обновление',
      'update_postpone': 'Отложить',
      'update_install': 'Установить',
      'update_notes': 'Что нового',
      'update_remind_later': 'Напомним позже',
      'sync_and_share': 'Синхронизация и обмен',
      'sync': 'Синхронизация',
      'sync_device_name': 'Имя устройства',
      'sync_secret': 'PIN / Общий секрет',
      'sync_secret_hint': 'Оставьте пустым для открытой сети',
      'sync_send_success': 'Отправлено на',
      'sync_send_failed': 'Отправка не удалась',
      'sync_peers': 'Устройства рядом',
      'no_peers': 'Устройства не обнаружены. Убедитесь, что синхронизация включена на другом устройстве.',
      'refresh': 'Обновить',
      'export_data': 'Экспорт данных',
      'export_success': 'Файл экспорта готов к отправке',
      'export_failed': 'Ошибка экспорта',
      'import_data': 'Импорт данных',
      'import_success': 'Данные успешно импортированы',
      'import_failed': 'Ошибка импорта',
      'send_logs': 'Отправить логи разработчику',
      'logs_sent': 'Логи отправлены',
      'logs_failed': 'Не удалось отправить логи',
      'paste': 'Вставить',
      'paste_error': 'Буфер обмена пуст или не содержит текста',
      'default_icon': 'Иконка по умолчанию',
      'folder_icon': 'Иконка папки',
      'icon_study': 'Учёба',
      'icon_shopping': 'Покупки',
      'icon_work': 'Работа',
      'icon_home': 'Дом',
      'icon_health': 'Здоровье',
      'icon_travel': 'Путешествия',
      'icon_sport': 'Спорт',
      'add_to_calendar': 'Добавить в календарь',
      'remove_from_calendar': 'Убрать из календаря',
      'calendar_no_permission': 'Нет разрешения на работу с календарём',
      'calendar_select': 'Выберите календарь',
      'calendar_no_calendars': 'Календари не найдены',
      'set_time': 'Установить время',
      'duration': 'Длительность',
      'duration_error': 'Неверный формат. Примеры: 1:30, 90, 1h30',
      'invalid_period': 'Конец периода должен быть позже начала',
      'time_period': 'Период',
      'no_duration': 'Не задана',
      'start_time': 'Начало',
      'end_time': 'Конец',
      'clear': 'Очистить',
      'time': 'Время',
    },
    'en': {
      'search': 'Search',
      'tasks': 'Tasks',
      'settings': 'Settings',
      'create_folder': 'Create folder',
      'create_task': 'Create task',
      'new_task': 'new task...',
      'new_folder': 'new folder...',
      'delete': 'Delete',
      'edit': 'Edit',
      'edit_task': 'Edit task',
      'edit_folder': 'Edit folder',
      'delete_folder': 'Delete folder',
      'cancel': 'Cancel',
      'save': 'Save',
      'empty_list': 'List is empty',
      'nothing_found': 'Nothing found',
      'filters': 'Filters',
      'filter_all': 'All',
      'filter_active': 'In progress',
      'filter_completed': 'Completed',
      'filter_folders': 'Folders only',
      'change_avatar': 'Change avatar',
      'notifications': 'Notifications',
      'profile': 'Profile',
      'appearance': 'Appearance',
      'widgets': 'Widgets',
      'notifications_and_data': 'Notifications & Data',
      'other': 'Other',
      'theme': 'App theme',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_system': 'System',
      'data_management': 'Data management',
      'language': 'Language',
      'lang_name': 'English',
      'animation_speed': 'Animation speed',
      'speed_fast': 'Fast',
      'speed_normal': 'Normal',
      'speed_slow': 'Slow',
      'speed_custom': 'Custom',
      'app_scale': 'Interface scale',
      'scale_small': 'Small',
      'scale_default': 'Default',
      'scale_large': 'Large',
      'scale_custom': 'Custom',
      'about': 'About app',
      'about_title': 'About ASA App',
      'about_desc': 'ASA is a modern task manager supporting folders and flexible filtering.',
      'version': 'Version 1.1.0',
      'clear_tasks': 'Clear all tasks',
      'clear_folders': 'Clear all folders',
      'clear_all': 'Reset all data',
      'confirm_clear': 'Are you sure?',
      'folder_title': 'Folder: ',
      'no_tasks_in_folder': 'No tasks in this folder yet',
      'add_task_to_folder': 'Add task to folder',
      'back': 'Back',
      'confirm_delete_title': 'Delete',
      'confirm_delete_content': 'Are you sure you want to delete this?',
      'speed_range': 'from 0.1 to 5.0',
      'speed_error': 'Value must be between 0.1 and 5.0',
      'scale_error': 'Value must be within the allowed range',
      'save_btn': 'Save',
      'streak_info': 'About streak',
      'task_moved': 'Task moved to',
      'folder_moved': 'Folder moved to',
      'widget': 'Widget',
      'show_in_widget': 'Show tasks in widget',
      'widget_mode': 'What to display',
      'widget_mode_streak': 'Streak',
      'widget_mode_active_tasks': 'Active tasks',
      'widget_mode_last_folder': 'Last folder',
      'widget_disabled': 'Widget disabled',
      'widget_last_folder': 'Last folder',
      'update_available': 'Update available',
      'update_postpone': 'Postpone',
      'update_install': 'Install',
      'update_notes': 'What\'s new',
      'update_remind_later': 'Remind later',
      'sync_and_share': 'Sync & Share',
      'sync': 'Sync',
      'sync_device_name': 'Device name',
      'sync_secret': 'PIN / Shared secret',
      'sync_secret_hint': 'Leave empty for open network',
      'sync_send_success': 'Sent to',
      'sync_send_failed': 'Send failed',
      'sync_peers': 'Nearby devices',
      'no_peers': 'No devices found. Make sure sync is enabled on the other device.',
      'refresh': 'Refresh',
      'export_data': 'Export data',
      'export_success': 'Export file ready to share',
      'export_failed': 'Export failed',
      'import_data': 'Import data',
      'import_success': 'Data imported successfully',
      'import_failed': 'Import failed',
      'send_logs': 'Send logs to developer',
      'logs_sent': 'Logs sent',
      'logs_failed': 'Failed to send logs',
      'paste': 'Paste',
      'paste_error': 'Clipboard is empty or does not contain text',
      'default_icon': 'Default icon',
      'folder_icon': 'Folder icon',
      'icon_study': 'Study',
      'icon_shopping': 'Shopping',
      'icon_work': 'Work',
      'icon_home': 'Home',
      'icon_health': 'Health',
      'icon_travel': 'Travel',
      'icon_sport': 'Sport',
      'add_to_calendar': 'Add to calendar',
      'remove_from_calendar': 'Remove from calendar',
      'calendar_no_permission': 'Calendar permission denied',
      'calendar_select': 'Select calendar',
      'calendar_no_calendars': 'No calendars found',
      'set_time': 'Set time',
      'duration': 'Duration',
      'duration_error': 'Invalid format. Examples: 1:30, 90, 1h30',
      'invalid_period': 'End time must be after start time',
      'time_period': 'Time period',
      'no_duration': 'Not set',
      'start_time': 'Start',
      'end_time': 'End',
      'clear': 'Clear',
      'time': 'Time',
    },
  };

  static String get(String key, String lang) {
    return _localizedValues[lang]?[key] ?? _localizedValues['ru']?[key] ?? key;
  }
}
