class AppStrings {
  static final Map<String, Map<String, String>> _localizedValues = {
    'ru': {
      'search': 'Поиск',
      'tasks': 'Задачи',
      'settings': 'Настройки',
      'create_folder': 'Создать папку',
      'create_task': 'Создать задачу',
      'new_task': 'новая задача...',
      'new_folder': 'новая папка...',
      'delete': 'Удалить',
      'edit': 'Редактировать',
      'edit_task': 'Редактировать задачу',
      'edit_folder': 'Редактировать папку',
      'more_options': 'Дополнительные действия',
      'reorder_item': 'Изменить порядок',
      'delete_folder': 'Удалить папку',
      'delete_custom_value_title': 'Удалить пользовательское значение?',
      'delete_custom_value_content':
          'Это значение будет удалено из списка сохранённых параметров.',
      'cancel': 'Отмена',
      'save': 'Сохранить',
      'add': 'Добавить',
      'remove': 'Удалить',
      'remove_attachment': 'Удалить вложение',
      'add_information': 'Добавить информацию',
      'additional_information': 'Дополнительная информация',
      'attachments': 'Вложения',
      'quantity_block': 'Количество',
      'quantity_block_limit': 'Можно добавить не больше 3 блоков количества',
      'description_block': 'Описание',
      'quantity_label': 'Название показателя',
      'quantity_current': 'Текущее значение',
      'quantity_target': 'Целевое значение',
      'quantity_unit': 'Что считаем?',
      'quantity_unit_hint': 'Например: страницы, стаканы или минуты',
      'quantity_unit_times': 'Раз',
      'quantity_unit_minutes': 'Минуты',
      'quantity_unit_hours': 'Часы',
      'quantity_unit_pages': 'Страницы',
      'quantity_unit_steps': 'Шаги',
      'quantity_unit_glasses': 'Стаканы',
      'quantity_unit_kilograms': 'Килограммы (кг)',
      'quantity_unit_kilometers': 'Километры (км)',
      'quantity_unit_custom': 'Другое…',
      'quantity_custom_unit': 'Своя единица',
      'quantity_custom_unit_hint': 'Например: книги, задачи или яблоки',
      'quantity_decrease': 'Уменьшить количество',
      'quantity_increase': 'Увеличить количество',
      'description_text': 'Описание задачи',
      'description_source': 'Исходник',
      'description_preview': 'Предпросмотр',
      'description_bold': 'Жирный',
      'description_italic': 'Курсив',
      'description_code': 'Код',
      'description_bulleted_list': 'Маркированный список',
      'description_quote': 'Цитата',
      'description_link': 'Ссылка',
      'description_formatting': 'Форматирование Markdown',
      'description_tags': 'Теги',
      'description_backlinks': 'Обратные ссылки',
      'description_related': 'Похожие задачи',
      'knowledge_search': 'Поиск по знаниям',
      'knowledge_search_hint': 'Поиск по задачам и описаниям',
      'knowledge_search_empty': 'Совпадений не найдено',
      'knowledge_match_title': 'Название',
      'knowledge_match_folder': 'Папка',
      'knowledge_match_tag': 'Тег',
      'knowledge_match_description': 'Описание',
      'add_link': 'Добавить ссылку',
      'add_image': 'Добавить изображение',
      'add_file': 'Добавить файл',
      'invalid_link': 'Введите корректную ссылку http или https',
      'invalid_quantity': 'Введите корректное значение количества',
      'required_field': 'Заполните поле',
      'attachment_unavailable': 'Не удалось добавить или открыть вложение',
      'attachment_limit': 'Достигнут лимит в 20 вложений',
      'attachment_mention_title': 'Вложения',
      'attachment_mention_empty': 'Вложений не найдено',
      'attachment_type_link': 'Ссылка',
      'attachment_type_image': 'Изображение',
      'attachment_type_file': 'Файл',
      'full_description': 'Полное описание',
      'description_link_ambiguous': 'Ссылка неоднозначна',
      'description_link_unresolved': 'Ссылка не найдена',
      'description_tag': 'Тег',
      'description_missing_attachment': 'Вложение недоступно',
      'description_callout_note': 'Заметка',
      'description_callout_tip': 'Совет',
      'description_callout_warning': 'Предупреждение',
      'description_callout_important': 'Важно',
      'description_callout_quote': 'Цитата',
      'unknown_attachment': 'Вложение недоступно',
      'viewer_copy': 'Копировать',
      'viewer_copied': 'Скопировано',
      'viewer_pdf_error': 'Не удалось открыть PDF-файл',
      'viewer_pdf_unavailable': 'PDF-файл недоступен для просмотра',
      'viewer_office_file':
          'Откройте документ в установленном приложении Office',
      'viewer_archive_file':
          'Архив можно открыть во внешнем файловом менеджере',
      'viewer_generic_file': 'Для этого файла нужен внешний просмотрщик',
      'viewer_external_hint': 'Выберите действие для продолжения',
      'viewer_open_external': 'Открыть внешним приложением',
      'viewer_share': 'Поделиться файлом',
      'viewer_external_open_failed':
          'Не удалось открыть файл во внешнем приложении',
      'viewer_file_unavailable': 'Файл недоступен',
      'viewer_share_failed': 'Не удалось поделиться файлом',
      'browser_back': 'Назад',
      'browser_forward': 'Вперёд',
      'browser_reload': 'Обновить',
      'browser_open_external': 'Открыть во внешнем браузере',
      'browser_not_supported':
          'Встроенный просмотр недоступен на этой платформе. Откройте ссылку во внешнем браузере.',
      'browser_load_error': 'Не удалось загрузить страницу',
      'browser_retry': 'Повторить',
      'browser_external_failed': 'Не удалось открыть внешний браузер',
      'browser_secure_connection': 'Защищённое соединение с {domain}',
      'empty_list': 'Список пуст',
      'nothing_found': 'Ничего не найдено',
      'filters': 'Фильтры',
      'filter_all': 'Все',
      'filter_active': 'В процессе',
      'filter_completed': 'Завершенные',
      'filter_folders': 'Только папки',
      'change_avatar': 'Сменить аватар',
      'avatar_invalid_format':
          'Неподдерживаемый формат. Используйте JPEG, PNG, GIF или WebP',
      'avatar_too_large': 'Файл аватара слишком большой',
      'notifications': 'Уведомления',
      'notifications_permission_needed': 'Уведомления отключены',
      'notifications_permission_hint':
          'Разрешение отключено в настройках системы. Откройте настройки, чтобы включить уведомления.',
      'open_settings': 'Открыть настройки',
      'profile': 'Профиль',
      'appearance': 'Внешний вид',
      'widgets': 'Виджеты',
      'notifications_and_data': 'Уведомления и данные',
      'other': 'Другое',
      'theme': 'Тема приложения',
      'theme_light': 'Светлая',
      'theme_dark': 'Тёмная',
      'theme_system': 'Системная',
      'color_palette': 'Палитра',
      'palette_base': 'Базовая',
      'palette_base_description': 'Текущая цветовая схема приложения',
      'palette_ocean': 'Ocean',
      'palette_ocean_description': 'Чистая синяя палитра',
      'palette_custom': 'Своя палитра',
      'palette_custom_description': 'Пользовательские цвета',
      'color_palette_hint': 'Выберите схему или настройте до трёх цветов',
      'palette_custom_limit': 'Максимум 3 цвета, формат #RRGGBB',
      'add_custom_palette': 'Добавить свою палитру',
      'edit_custom_palette': 'Изменить свою палитру',
      'custom_palette_title': 'Своя палитра',
      'custom_palette_hint': 'Добавьте от 1 до 3 непрозрачных цветов',
      'color_hex': 'Цвет',
      'add_color': 'Добавить цвет',
      'palette_invalid_color': 'Введите цвет в формате #RRGGBB',
      'palette_duplicate_color': 'Цвета не должны повторяться',
      'palette_min_colors': 'Добавьте хотя бы один цвет',
      'data_management': 'Управление данными',
      'language': 'Язык',
      'lang_name': 'русский',
      'animation_speed': 'Плавность анимации',
      'speed_fast': 'Быстро',
      'speed_normal': 'Обычно',
      'speed_slow': 'Медленно',
      'speed_custom': 'Своя',
      'app_scale': 'Масштаб интерфейса',
      'scale_small': 'Мелкий',
      'scale_default': 'Стандарт',
      'scale_large': 'Крупный',
      'scale_custom': 'Свой',
      'about': 'О приложении',
      'about_title': 'О приложении ASA',
      'about_desc':
          'ASA — современный менеджер задач с поддержкой папок и гибкой фильтрацией.',
      'version': 'Версия',
      'clear_tasks': 'Очистить все задачи',
      'clear_folders': 'Очистить все папки',
      'clear_all': 'Сбросить все данные',
      'confirm_clear': 'Вы уверены?',
      'folder_title': 'Папка: ',
      'no_tasks_in_folder': 'В этой папке пока нет задач',
      'streak_folder_subfolder_denied':
          'В системной папке нельзя создавать подпапки',
      'add_task_to_folder': 'Добавить задачу в папку',
      'back': 'Назад',
      'confirm_delete_title': 'Удаление',
      'confirm_delete_content': 'Вы уверены, что хотите удалить это?',
      'speed_range': 'от 0.1 до 5.0',
      'speed_error': 'Значение должно быть от 0.1 до 5.0',
      'scale_error': 'Значение должно быть в пределах допустимого диапазона',
      'save_btn': 'Сохранить',
      'task_moved': 'Задача перенесена в',
      'folder_moved': 'Папка перенесена в',
      'move_denied': 'Сюда переместить нельзя',
      'task_move_to_root_denied': 'Задачу нельзя перенести на главный экран',
      'move_to_parent': 'На уровень выше',
      'task_moved_to_parent': 'Задача перемещена на уровень выше',
      'folder_moved_to_parent': 'Папка перемещена на уровень выше',
      'widget': 'Виджет',
      'show_in_widget': 'Показывать задачи в виджете',
      'widget_mode': 'Что отображать',
      'widget_mode_active_tasks': 'Активные задачи',
      'widget_mode_last_folder': 'Последняя папка',
      'widget_disabled': 'Виджет выключен',
      'widget_last_folder': 'Последняя папка',
      'update_available': 'Доступно обновление',
      'update_postpone': 'Отложить',
      'update_install': 'Установить',
      'update_notes': 'Что нового',
      'update_remind_later': 'Напомним позже',
      'update_downloading': 'Загрузка обновления…',
      'update_download_failed': 'Не удалось загрузить обновление',
      'update_unavailable_platform':
          'Автоустановка недоступна на этой платформе',
      'check_for_updates': 'Проверить обновления',
      'install_update_version': 'Установить обновление (v{version})',
      'up_to_date_message': 'У вас установлена последняя версия (v{version})',
      'checking_updates': 'Проверка…',
      'check_cooldown_message':
          'Повторная проверка доступна через {seconds} сек.',
      'load_more': 'Загрузить ещё',
      'view_all_versions': 'Все версии',
      'whats_new': 'Что нового',
      'releases_empty': 'Релизов пока нет',
      'releases_error': 'Не удалось загрузить историю версий',
      'retry': 'Повторить',
      'published': 'Опубликовано',
      'sync_and_share': 'Синхронизация и обмен',
      'sync': 'Синхронизация',
      'sync_device_name': 'Имя устройства',
      'sync_secret': 'PIN / Общий секрет',
      'sync_secret_hint': 'Оставьте пустым для открытой сети',
      'sync_send_success': 'Отправлено на',
      'sync_send_failed': 'Отправка не удалась',
      'sync_start_failed': 'Не удалось запустить синхронизацию',
      'sync_permission_denied':
          'Для синхронизации нужен доступ к устройствам в локальной сети',
      'sync_peers': 'Устройства рядом',
      'no_peers':
          'Устройства не обнаружены. Убедитесь, что синхронизация включена на другом устройстве.',
      'refresh': 'Обновить',
      'export_data': 'Экспорт данных',
      'export_success': 'Файл экспорта готов к отправке',
      'export_failed': 'Ошибка экспорта',
      'import_data': 'Импорт данных',
      'import_success': 'Данные успешно импортированы',
      'import_failed': 'Ошибка импорта',
      'error_invalid_extension':
          'Неверный формат файла. Ожидается .json или .asa',
      'error_file_too_large': 'Файл слишком большой',
      'error_not_utf8': 'Ошибка кодировки файла',
      'error_invalid_json': 'Некорректный JSON',
      'error_invalid_format': 'Неверный формат данных',
      'error_missing_keys': 'Отсутствуют обязательные поля',
      'error_invalid_lists': 'Списки задач или папок повреждены',
      'error_invalid_secret': 'Неверный ключ синхронизации',
      'error_missing_secret': 'Отсутствует ключ синхронизации',
      'error_import_failed': 'Не удалось импортировать данные',
      'import_preview_title': 'Импорт файла',
      'import_preview_file': 'Файл',
      'import_preview_size': 'Размер',
      'import_preview_version': 'Версия',
      'import_preview_exported_at': 'Дата экспорта',
      'import_preview_tasks': 'Задач',
      'import_preview_folders': 'Папок',
      'import_preview_status': 'Статус',
      'import_preview_valid': 'Файл можно импортировать',
      'import_preview_invalid': 'Не удалось прочитать файл',
      'import_preview_confirm': 'Импортировать',
      'import_preview_cancel': 'Отмена',
      'send_logs': 'Отправить отчёт разработчику',
      'send_logs_title': 'Отправить диагностический отчёт?',
      'send_logs_warning':
          'Будут отправлены только технические данные и последние ошибки. Задачи, описания, вложения и резервные копии не отправляются.',
      'send_logs_confirm': 'Отправить отчёт',
      'logs_sent': 'Отчёт отправлен',
      'logs_failed': 'Не удалось отправить отчёт',
      'paste': 'Вставить',
      'paste_error': 'Буфер обмена пуст или не содержит текста',
      'default_icon': 'Иконка по умолчанию',
      'folder_icon': 'Иконка папки',
      'icon_study': 'Учёба',
      'icon_shopping': 'Покупки',
      'icon_work': 'Работа',
      'icon_home': 'Дом',
      'icon_health': 'Здоровье',
      'icon_travel': 'Путешествия',
      'icon_sport': 'Спорт',
      'add_to_calendar': 'Добавить в календарь',
      'remove_from_calendar': 'Убрать из календаря',
      'calendar_no_permission': 'Нет разрешения на работу с календарём',
      'calendar_permission_hint':
          'Разрешите ASA доступ к календарю в настройках приложения, чтобы добавлять задачи в события.',
      'calendar_select': 'Выберите календарь',
      'calendar_no_calendars': 'Нет доступных календарей для записи',
      'set_time': 'Установить время',
      'duration': 'Плановая длительность',
      'invalid_period': 'Начало и конец периода не должны совпадать',
      'time_period': 'Период',
      'no_duration': 'Не задана',
      'start_time': 'Начало',
      'end_time': 'Конец',
      'timer_start': 'Запустить таймер',
      'timer_stop': 'Остановить таймер',
      'timer_reset': 'Сбросить таймер',
      'timer_running': 'Таймер запущен',
      'timer_ready': 'Фактическое время',
      'actual_time': 'Фактическое время',
      'clear': 'Очистить',
      'time': 'Время',
      'task_details': 'Детали задачи',
      'task_status': 'Статус',
      'status_completed': 'Выполнено',
      'status_active': 'В процессе',
      'folder': 'Папка',
      'no_folder': 'Без папки',
      'created_at': 'Создана',
      'updated_at': 'Обновлена',
      'calendar_status': 'Календарь',
      'calendar_linked': 'Связана',
      'due_date': 'Дата',
      'calendar_not_linked': 'Не связана',
      'setup_title': 'Быстрая настройка',
      'setup_continue': 'Продолжить',
      'setup_skip': 'Пропустить',
      'setup_enable': 'Включить',
      'setup_footer':
          'После завершения настройки разрешения можно изменить в разделе «Уведомления и данные»',
      'setup_battery': 'Отключить ограничение батареи',
      'setup_battery_subtitle':
          'Нужно чтобы напоминания приходили вовремя, даже когда приложение закрыто',
      'setup_autostart': 'Автозапуск',
      'setup_autostart_subtitle':
          'Требуется на устройствах Xiaomi/HyperOS для получения уведомлений после перезагрузки',
      'setup_autostart_confirm_title': 'Автозапуск включён?',
      'setup_autostart_confirm_content':
          'Проверьте, что для ASA включён автозапуск в системных настройках. Подтверждайте только после этого.',
      'setup_autostart_confirm': 'Я включил автозапуск',
      'setup_autostart_failed': 'Не удалось открыть настройки автозапуска',
      'setup_exact_alarm': 'Точные будильники и напоминания',
      'setup_exact_alarm_subtitle':
          'Разрешение на срабатывание уведомлений секунда в секунду (Android 12+)',
      'setup_grant_all': 'Выдайте все разрешения для продолжения',
      'setup_notification_denied':
          'Разрешение на уведомления не выдано — повторите попытку',
      'setup_notification_permanently_denied':
          'Уведомления отключены в системе. Включите их в настройках приложения',
    },
    'en': {
      'search': 'Search',
      'tasks': 'Tasks',
      'settings': 'Settings',
      'create_folder': 'Create folder',
      'create_task': 'Create task',
      'new_task': 'new task...',
      'new_folder': 'new folder...',
      'delete': 'Delete',
      'edit': 'Edit',
      'edit_task': 'Edit task',
      'edit_folder': 'Edit folder',
      'more_options': 'More options',
      'reorder_item': 'Reorder item',
      'delete_folder': 'Delete folder',
      'delete_custom_value_title': 'Delete custom value?',
      'delete_custom_value_content':
          'This value will be removed from the saved settings.',
      'cancel': 'Cancel',
      'save': 'Save',
      'add': 'Add',
      'remove': 'Remove',
      'remove_attachment': 'Remove attachment',
      'add_information': 'Add information',
      'additional_information': 'Additional information',
      'attachments': 'Attachments',
      'quantity_block': 'Quantity',
      'quantity_block_limit': 'You can add no more than 3 quantity blocks',
      'description_block': 'Description',
      'quantity_label': 'Metric name',
      'quantity_current': 'Current value',
      'quantity_target': 'Target value',
      'quantity_unit': 'What are we counting?',
      'quantity_unit_hint': 'For example: pages, glasses, or minutes',
      'quantity_unit_times': 'Times',
      'quantity_unit_minutes': 'Minutes',
      'quantity_unit_hours': 'Hours',
      'quantity_unit_pages': 'Pages',
      'quantity_unit_steps': 'Steps',
      'quantity_unit_glasses': 'Glasses',
      'quantity_unit_kilograms': 'Kilograms (kg)',
      'quantity_unit_kilometers': 'Kilometers (km)',
      'quantity_unit_custom': 'Other…',
      'quantity_custom_unit': 'Custom unit',
      'quantity_custom_unit_hint': 'For example: books, tasks, or apples',
      'quantity_decrease': 'Decrease quantity',
      'quantity_increase': 'Increase quantity',
      'description_text': 'Task description',
      'description_source': 'Source',
      'description_preview': 'Preview',
      'description_bold': 'Bold',
      'description_italic': 'Italic',
      'description_code': 'Code',
      'description_bulleted_list': 'Bulleted list',
      'description_quote': 'Quote',
      'description_link': 'Link',
      'description_formatting': 'Markdown formatting',
      'description_tags': 'Tags',
      'description_backlinks': 'Backlinks',
      'description_related': 'Related tasks',
      'knowledge_search': 'Knowledge search',
      'knowledge_search_hint': 'Search tasks and descriptions',
      'knowledge_search_empty': 'No matching tasks found',
      'knowledge_match_title': 'Title',
      'knowledge_match_folder': 'Folder',
      'knowledge_match_tag': 'Tag',
      'knowledge_match_description': 'Description',
      'add_link': 'Add link',
      'add_image': 'Add image',
      'add_file': 'Add file',
      'invalid_link': 'Enter a valid http or https link',
      'invalid_quantity': 'Enter a valid quantity value',
      'required_field': 'Fill in this field',
      'attachment_unavailable': 'Could not add or open the attachment',
      'attachment_limit': 'The 20-attachment limit has been reached',
      'attachment_mention_title': 'Attachments',
      'attachment_mention_empty': 'No attachments found',
      'attachment_type_link': 'Link',
      'attachment_type_image': 'Image',
      'attachment_type_file': 'File',
      'full_description': 'Full description',
      'description_link_ambiguous': 'Ambiguous link',
      'description_link_unresolved': 'Link not found',
      'description_tag': 'Tag',
      'description_missing_attachment': 'Attachment unavailable',
      'description_callout_note': 'Note',
      'description_callout_tip': 'Tip',
      'description_callout_warning': 'Warning',
      'description_callout_important': 'Important',
      'description_callout_quote': 'Quote',
      'unknown_attachment': 'Attachment unavailable',
      'viewer_copy': 'Copy',
      'viewer_copied': 'Copied',
      'viewer_pdf_error': 'Could not open the PDF file',
      'viewer_pdf_unavailable': 'The PDF file is unavailable for viewing',
      'viewer_office_file': 'Open this document in an installed Office app',
      'viewer_archive_file': 'Open this archive in an external file manager',
      'viewer_generic_file': 'This file requires an external viewer',
      'viewer_external_hint': 'Choose an action to continue',
      'viewer_open_external': 'Open with external app',
      'viewer_share': 'Share file',
      'viewer_external_open_failed': 'Could not open the file externally',
      'viewer_file_unavailable': 'File unavailable',
      'viewer_share_failed': 'Could not share the file',
      'browser_back': 'Back',
      'browser_forward': 'Forward',
      'browser_reload': 'Reload',
      'browser_open_external': 'Open in external browser',
      'browser_not_supported':
          'In-app viewing is unavailable on this platform. Open the link in an external browser.',
      'browser_load_error': 'Could not load the page',
      'browser_retry': 'Retry',
      'browser_external_failed': 'Could not open the external browser',
      'browser_secure_connection': 'Secure connection to {domain}',
      'empty_list': 'List is empty',
      'nothing_found': 'Nothing found',
      'filters': 'Filters',
      'filter_all': 'All',
      'filter_active': 'In progress',
      'filter_completed': 'Completed',
      'filter_folders': 'Folders only',
      'change_avatar': 'Change avatar',
      'avatar_invalid_format':
          'Unsupported format. Use JPEG, PNG, GIF, or WebP',
      'avatar_too_large': 'Avatar file is too large',
      'notifications': 'Notifications',
      'notifications_permission_needed': 'Notifications are off',
      'notifications_permission_hint':
          'Permission is disabled in system settings. Open settings to enable notifications.',
      'open_settings': 'Open settings',
      'profile': 'Profile',
      'appearance': 'Appearance',
      'widgets': 'Widgets',
      'notifications_and_data': 'Notifications & Data',
      'other': 'Other',
      'theme': 'App theme',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_system': 'System',
      'color_palette': 'Color palette',
      'palette_base': 'Base',
      'palette_base_description': 'The current app color scheme',
      'palette_ocean': 'Ocean',
      'palette_ocean_description': 'A clean blue palette',
      'palette_custom': 'Custom palette',
      'palette_custom_description': 'User-defined colors',
      'color_palette_hint': 'Choose a scheme or configure up to three colors',
      'palette_custom_limit': 'Up to 3 colors, #RRGGBB format',
      'add_custom_palette': 'Add custom palette',
      'edit_custom_palette': 'Edit custom palette',
      'custom_palette_title': 'Custom palette',
      'custom_palette_hint': 'Add 1 to 3 opaque colors',
      'color_hex': 'Color',
      'add_color': 'Add color',
      'palette_invalid_color': 'Enter a color in #RRGGBB format',
      'palette_duplicate_color': 'Colors must be unique',
      'palette_min_colors': 'Add at least one color',
      'data_management': 'Data management',
      'language': 'Language',
      'lang_name': 'English',
      'animation_speed': 'Animation speed',
      'speed_fast': 'Fast',
      'speed_normal': 'Normal',
      'speed_slow': 'Slow',
      'speed_custom': 'Custom',
      'app_scale': 'Interface scale',
      'scale_small': 'Small',
      'scale_default': 'Default',
      'scale_large': 'Large',
      'scale_custom': 'Custom',
      'about': 'About app',
      'about_title': 'About ASA App',
      'about_desc':
          'ASA is a modern task manager supporting folders and flexible filtering.',
      'version': 'Version',
      'clear_tasks': 'Clear all tasks',
      'clear_folders': 'Clear all folders',
      'clear_all': 'Reset all data',
      'confirm_clear': 'Are you sure?',
      'folder_title': 'Folder: ',
      'no_tasks_in_folder': 'No tasks in this folder yet',
      'streak_folder_subfolder_denied':
          'Cannot create subfolders in a system folder',
      'add_task_to_folder': 'Add task to folder',
      'back': 'Back',
      'confirm_delete_title': 'Delete',
      'confirm_delete_content': 'Are you sure you want to delete this?',
      'speed_range': 'from 0.1 to 5.0',
      'speed_error': 'Value must be between 0.1 and 5.0',
      'scale_error': 'Value must be within the allowed range',
      'save_btn': 'Save',
      'task_moved': 'Task moved to',
      'folder_moved': 'Folder moved to',
      'move_denied': 'Cannot move here',
      'task_move_to_root_denied': 'Tasks cannot be moved to the main screen',
      'move_to_parent': 'Move up one level',
      'task_moved_to_parent': 'Task moved up one level',
      'folder_moved_to_parent': 'Folder moved up one level',
      'widget': 'Widget',
      'show_in_widget': 'Show tasks in widget',
      'widget_mode': 'What to display',
      'widget_mode_active_tasks': 'Active tasks',
      'widget_mode_last_folder': 'Last folder',
      'widget_disabled': 'Widget disabled',
      'widget_last_folder': 'Last folder',
      'update_available': 'Update available',
      'update_postpone': 'Postpone',
      'update_install': 'Install',
      'update_notes': 'What\'s new',
      'update_remind_later': 'Remind later',
      'update_downloading': 'Downloading update…',
      'update_download_failed': 'Failed to download the update',
      'update_unavailable_platform':
          'In-app install is not available on this platform',
      'check_for_updates': 'Check for updates',
      'install_update_version': 'Install update (v{version})',
      'up_to_date_message': 'You already have the latest version (v{version})',
      'checking_updates': 'Checking…',
      'check_cooldown_message':
          'Re-checking will be available in {seconds} sec.',
      'load_more': 'Load more',
      'view_all_versions': 'All versions',
      'whats_new': "What's New",
      'releases_empty': 'No releases yet',
      'releases_error': 'Could not load release history',
      'retry': 'Retry',
      'published': 'Published',
      'sync_and_share': 'Sync & Share',
      'sync': 'Sync',
      'sync_device_name': 'Device name',
      'sync_secret': 'PIN / Shared secret',
      'sync_secret_hint': 'Leave empty for open network',
      'sync_send_success': 'Sent to',
      'sync_send_failed': 'Send failed',
      'sync_start_failed': 'Could not start sync',
      'sync_permission_denied':
          'Local network access is needed to discover sync devices',
      'sync_peers': 'Nearby devices',
      'no_peers':
          'No devices found. Make sure sync is enabled on the other device.',
      'refresh': 'Refresh',
      'export_data': 'Export data',
      'export_success': 'Export file ready to share',
      'export_failed': 'Export failed',
      'import_data': 'Import data',
      'import_success': 'Data imported successfully',
      'import_failed': 'Import failed',
      'error_invalid_extension': 'Invalid file format. Expected .json or .asa',
      'error_file_too_large': 'File is too large',
      'error_not_utf8': 'File encoding error',
      'error_invalid_json': 'Invalid JSON data',
      'error_invalid_format': 'Invalid data format',
      'error_missing_keys': 'Missing required data fields',
      'error_invalid_lists': 'Task or folder lists are corrupted',
      'error_invalid_secret': 'Invalid sync secret',
      'error_missing_secret': 'Missing sync secret',
      'error_import_failed': 'Failed to import data',
      'import_preview_title': 'Import file',
      'import_preview_file': 'File',
      'import_preview_size': 'Size',
      'import_preview_version': 'Version',
      'import_preview_exported_at': 'Exported at',
      'import_preview_tasks': 'Tasks',
      'import_preview_folders': 'Folders',
      'import_preview_status': 'Status',
      'import_preview_valid': 'Ready to import',
      'import_preview_invalid': 'Could not read file',
      'import_preview_confirm': 'Import',
      'import_preview_cancel': 'Cancel',
      'send_logs': 'Send diagnostic report',
      'send_logs_title': 'Send diagnostic report?',
      'send_logs_warning':
          'Only technical data and recent errors will be sent. Tasks, descriptions, attachments, and backups are not included.',
      'send_logs_confirm': 'Send report',
      'logs_sent': 'Report sent',
      'logs_failed': 'Failed to send report',
      'paste': 'Paste',
      'paste_error': 'Clipboard is empty or does not contain text',
      'default_icon': 'Default icon',
      'folder_icon': 'Folder icon',
      'icon_study': 'Study',
      'icon_shopping': 'Shopping',
      'icon_work': 'Work',
      'icon_home': 'Home',
      'icon_health': 'Health',
      'icon_travel': 'Travel',
      'icon_sport': 'Sport',
      'add_to_calendar': 'Add to calendar',
      'remove_from_calendar': 'Remove from calendar',
      'calendar_no_permission': 'Calendar permission denied',
      'calendar_permission_hint':
          'Allow ASA to access your calendar in app settings to add tasks to events.',
      'calendar_select': 'Select calendar',
      'calendar_no_calendars': 'No writable calendars found',
      'set_time': 'Set time',
      'duration': 'Planned duration',
      'invalid_period': 'Start and end of the period must be different',
      'time_period': 'Time period',
      'no_duration': 'Not set',
      'start_time': 'Start',
      'end_time': 'End',
      'timer_start': 'Start timer',
      'timer_stop': 'Stop timer',
      'timer_reset': 'Reset timer',
      'timer_running': 'Timer running',
      'timer_ready': 'Actual time',
      'actual_time': 'Actual time',
      'clear': 'Clear',
      'time': 'Time',
      'task_details': 'Task details',
      'task_status': 'Status',
      'status_completed': 'Completed',
      'status_active': 'In progress',
      'folder': 'Folder',
      'no_folder': 'No folder',
      'created_at': 'Created',
      'updated_at': 'Updated',
      'calendar_status': 'Calendar',
      'calendar_linked': 'Linked',
      'due_date': 'Due date',
      'calendar_not_linked': 'Not linked',
      'setup_title': 'Quick Setup',
      'setup_continue': 'Continue',
      'setup_skip': 'Skip',
      'setup_enable': 'Enable',
      'setup_footer':
          'After setup, you can change permissions in «Notifications & Data»',
      'setup_battery': 'Disable battery optimization',
      'setup_battery_subtitle':
          'Required for reminders to arrive on time, even when the app is closed',
      'setup_autostart': 'Auto-start',
      'setup_autostart_subtitle':
          'Required on Xiaomi/HyperOS to receive notifications after reboot',
      'setup_autostart_confirm_title': 'Is auto-start enabled?',
      'setup_autostart_confirm_content':
          'Verify that auto-start is enabled for ASA in system settings. Confirm only after doing so.',
      'setup_autostart_confirm': 'I enabled auto-start',
      'setup_autostart_failed': 'Could not open auto-start settings',
      'setup_exact_alarm': 'Exact alarms & reminders',
      'setup_exact_alarm_subtitle':
          'Permission for notifications to trigger down to the second (Android 12+)',
      'setup_grant_all': 'Grant all permissions to continue',
      'setup_notification_denied':
          'Notification permission was not granted — please try again',
      'setup_notification_permanently_denied':
          'Notifications are disabled in system settings. Enable them in the app settings',
    },
  };

  static String get(String key, String lang) {
    return _localizedValues[lang]?[key] ?? _localizedValues['ru']?[key] ?? key;
  }
}
